### ISSUE TITLE
Broken link on README.md

### ISSUE THREAD

**Issue by crossedheadx** [JaKooLit/Debian-Hyprland#1]
Hi, there's a broken link into README.md for Fedora repo.

**Comment by crossedheadx** [comment]
### Debian 13 Trixie- Hyprland install script based from my Fedora-Hyprland [`Link`](https://github.com/JaKooLit/Fedora-Hyprland) and Arch-Hyprland-v4 [`Link`](https://github.com/JaKooLit/Hyprland-v4)

**Comment by JaKooLit** [comment]
thanks bro. fixed
