### ISSUE TITLE
Give error

### ISSUE THREAD

**Issue by patatessss121aq** [JaKooLit/Debian-Hyprland#10]
Configuring libcudal: amd64

Conflicting nouveau kernel module loaded

The free nouveau kernel module is currently loaded and conflicts with the non-free nvidia kernel module.

The easiest way to fix this is to reboot the machine

It gives me such an error, what should I do? There is no response when I press the "OK" button and Linux does not allow shutting down or restarting. I am using Kali Linux.

I'm using translation, sorry if there is any mistake :')

**Comment by patatessss121aq** [comment]
> ctrl c ve betiğin değiştirilmesine izin vermenize izin verin ....
> 
> ve açıldıktan sonra yeniden başlatma ve tekrar çalıştırmalar daha iyi olur ....
> 
> bu hataların önlenmesi ve uzun süreli sorunların giderilmesini önlemek içindir, çünkü kuruluşta gösterilmiyor çalışmaktansa yeniden çalıştırılması daha iyidir

Thank you very much for your response so quickly. I'm in the classroom right now. The first thing you do when you get home is check it out.

**Comment by patatessss121aq** [comment]
> ctrl c ve betiğin tamamlanmasına izin verin ....
> 
> ve tamamlandıktan sonra yeniden başlatın ve tekrar çalıştırmaları daha iyi olur ....
> 
> bu hataları önlemek ve uzun süreli sorun gidermeyi önlemek içindir, çünkü neyin kurulu olmadığını bulmaya çalışmaktansa yeniden çalıştırmak daha iyidir

Now I have a bigger problem

Isn't this normal? I succeeded. Oh no hyoerlsnd it says XFCE when you enter this is what happens 
![IMG_20231204_221204](https://github.com/JaKooLit/Debian-Hyprland/assets/98663386/89390d7f-3aca-4c83-8afc-e13d4c23b8e6)
![Uploading IMG_20231204_221204.jpg…]()

**Comment by JaKooLit** [comment]
thats not an issue...

its just telling you that pywal is not initiated

wal -i wallpaper
