### ISSUE TITLE
[Bug]: Cannot Share the Screen

### ISSUE THREAD

**Issue by A-Akhil** [JaKooLit/Debian-Hyprland#106]
OS: Ubuntu 24.04 LTS x86_64 
Host: HP Pavilion Gaming Laptop 15-dk1xxx 
Kernel: 6.8.0-35-generic 
Shell: zsh 5.9 
DE: Hyprland 
WM: sway  CPU: Intel i5-10300H (8) @ 4.500GHz 
GPU: Intel CometLake-H GT2 [UHD Graphics] 
GPU: NVIDIA GeForce GTX 1650 Ti Mobil

**Comment by JaKooLit** [comment]
its not a bug

you just need to install obs and setup pipewire

**Comment by A-Akhil** [comment]
@JaKooLit i already have pipewire installed so what should i be doing is there any documentation which i can refer to

**Comment by JaKooLit** [comment]
https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/
