### ISSUE TITLE
[Docs]: Will the Ubuntu 24.04 upgrade/update in future break the installed hyprland?

### ISSUE THREAD

**Issue by tonyho** [JaKooLit/Debian-Hyprland#108]
Ubuntu would update day to day, will it break the installed hyprland using this repo?
Or how to recover it once it happened?

I thinks these info  may be added into the READ.md to make it much more clearly before users using chose the hyprland with this repo.

Thanks.

**Comment by JaKooLit** [comment]
pls go through readme..

it is stated in there packages which is built from source and not handled by ubuntu
