### ISSUE TITLE
[Feature Request]: Add input method IME support(Chinese Input method) for Ubuntu 24.04

### ISSUE THREAD

**Issue by tonyho** [JaKooLit/Debian-Hyprland#109]
### Description

It seems I cannot input the Chinese strings, as no ibus started, could you help to update the script or give a guide to let user using the ibus and ibus-intelligence-pinpyin or ibus-pinyin to input Chinese?

### Use Case

This would help non-English input users.

### Additional Information

Currently, I can input the Chinese when logging into the Ubuntu on Wayland DE using ibus and ibus-intelligence-pinyin.

**Comment by JaKooLit** [comment]
Im sorry, I cannot... and not planned since there are lots of language..
