### ISSUE TITLE
NVIDIA GPU not detected

### ISSUE THREAD

**Issue by liamrahum** [JaKooLit/Debian-Hyprland#11]
(Tested on Debian "trixie" testing) When launching Hyprland it crashes, and the log file ends with "0 gpus detected"
All the kernel parameters are in place - I made sure the firmware is installed for the nvidia modules, and of course I rebooted my computer for changes to take place.
Any idea how to fix it?

**Comment by JaKooLit** [comment]
sounds interesting....

But tbh I have no clue... 

on tty, can you check if nvidia drivers is properly installed?

nvidia-smi could be one way to find out

**Comment by liamrahum** [comment]
Closed issue, was fixed sorta randomly

First installed nvidia drivers on stable release - then upgraded to trixie

**Comment by t500s** [comment]
I have same behaviour. I don't have any ideas how to fix this.
