### ISSUE TITLE
[Bug]: Warning on sudo apt update - Ubuntu 24.04

### ISSUE THREAD

**Issue by Artur-Poffo** [JaKooLit/Debian-Hyprland#111]
### Description

When running `sudo apt update` in my terminal I received a warning stating that the repository is not signed

I'm kind of new to Linux so maybe this warning is normal but I decided to open the issue to clear up the doubt and help other lost people

Thats tool is amazing!!! 😀

**Warning on screenshot**

### Screenshots

![image](https://github.com/JaKooLit/Debian-Hyprland/assets/89012723/1327eced-8bcb-4f71-baf7-1586e5fde294)

### Environment

System: Ubuntu 24.04

**Comment by JaKooLit** [comment]
I do not understand why you add trixie repo? 


Kindly go through readme... Nowhere in the readme that I instructed to add additional repo

**Comment by Artur-Poffo** [comment]
uhhm, I believe this was already installed on my system before, do I need to do some procedure or just delete it?

**Comment by JaKooLit** [comment]
comment or delete that.. did you upgrade from 23.10?

suggest install a new ubuntu and follow the instruction on readme
