### ISSUE TITLE
pyprland not working

### ISSUE THREAD

**Issue by nirmaleeswar30** [JaKooLit/Debian-Hyprland#116]
when i do super+shift+enter or super+z i get pypr cant connect, is daemon running. I think it has to do with pyprland
![Screenshot_22-Jun_23-54-01_7212](https://github.com/JaKooLit/Debian-Hyprland/assets/148993853/7cc26e7d-0698-42b3-b5ee-c38f97320aa6)

**Comment by JaKooLit** [comment]
if it detects that its Debian / Ubuntu, the pyprland startup is disabled

see latest release notes

https://github.com/JaKooLit/Hyprland-Dots/releases/tag/v2.2.14


you can re enable again if wanted

~/.config/hypr/UserConfigs/StartupApps.conf

**Comment by nirmaleeswar30** [comment]
Thank you! will check it out.
