### ISSUE TITLE
[Bug]: Not able to screenshare during videocalls

### ISSUE THREAD

**Issue by belikedeep** [JaKooLit/Debian-Hyprland#119]
Unable to share screens during video calls:

Gmeet: Only able to share tabs, unable to share anything else
Slack: Cannot share entire screen, only tabs

**Comment by JaKooLit** [comment]
pls do not file screensharing problem to this project.

suggest you report to hyprland project.


by the way, make sure to follow this
https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/
