### ISSUE TITLE
Error setting value <$color2> for field <decoration:col shadow>

### ISSUE THREAD

**Issue by DanielYuan123** [JaKooLit/Debian-Hyprland#12]
Config error at line 56 (/home/XXXXX/config/hypr/configs/Settings.conf): Error setting value <$color2> for field <decoration:col shadow>.
stoll. Hyprland may not work correctly.
![ArcoLinux_2023-12-08_22-49-29](https://github.com/JaKooLit/Debian-Hyprland/assets/94063653/7b5b02d6-25c0-4492-b67e-109c402c46dc)

**Comment by JaKooLit** [comment]
dang lately seems the pywal is not installing properly

sudo apt install libdrm-dev python3-pip

sudo pip3 install pywal --break-system-packages



wal -i <any-wallpaper-including-path>

logout or reboot

**Comment by JaKooLit** [comment]
if its already installed did you ran

wal -i any wallpaper?

**Comment by Mathieux83** [comment]
Hi, same prob here.. 

1st one, when kitty show-up,

> cat: /home/m/.cache/wal/sequences: No such file or directory
> cat: /home/m/.cache/wal/sequences: No such file or directory
> /home/m/.zshrc:source:26: no such file or directory: /home/m/.cache/wal/colors-tty.sh

has u can see i don't have "sequences" folder or files idk and "colors-tty.sh"


> ..[m@Coucou-C-Moi] - [~] - [Sat Dec 09, 01:27]
> ..[$] <()> wal -i /home/m/Pictures/wallpapers/edger_lucy_neon.jpg
> [I] image: Using image edger_lucy_neon.jpg.
> [I] colors: Generating a colorscheme.
> [I] colors: Using wal backend.
> convert: Unrecognized option (-unique-colors).
> Traceback (most recent call last):
>   File "/usr/local/bin/wal", line 33, in <module>
>     sys.exit(load_entry_point('pywal==3.3.1', 'console_scripts', 'wal')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/pywal/__main__.py", line 208, in main
>     parse_args(parser)
>   File "/usr/local/lib/python3.11/dist-packages/pywal/__main__.py", line 163, in parse_args
>     colors_plain = colors.get(image_file, args.l, args.backend,
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/pywal/colors.py", line 144, in get
>     colors = getattr(backend, "get")(img, light)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/pywal/backends/wal.py", line 86, in get
>     colors = gen_colors(img)
>              ^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/pywal/backends/wal.py", line 41, in gen_colors
>     raw_colors = imagemagick(16 + i, img, magick_command)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/pywal/backends/wal.py", line 19, in imagemagick
>     return subprocess.check_output([*magick_command, img, *flags]).splitlines()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['convert', '/home/m/Pictures/wallpapers/edger_lucy_neon.jpg[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' returned non-zero exit status 1.

**Comment by JaKooLit** [comment]
> Hi, same prob here..
> 
> 1st one, when kitty show-up,
> 
> > cat: /home/m/.cache/wal/sequences: No such file or directory
> > cat: /home/m/.cache/wal/sequences: No such file or directory
> > /home/m/.zshrc:source:26: no such file or directory: /home/m/.cache/wal/colors-tty.sh
> 
> has u can see i don't have "sequences" folder or files idk and "colors-tty.sh"
> 
> > ..[m@Coucou-C-Moi] - [~] - [Sat Dec 09, 01:27]
> > ..[$] <()> wal -i /home/m/Pictures/wallpapers/edger_lucy_neon.jpg
> > [I] image: Using image edger_lucy_neon.jpg.
> > [I] colors: Generating a colorscheme.
> > [I] colors: Using wal backend.
> > convert: Unrecognized option (-unique-colors).
> > Traceback (most recent call last):
> > File "/usr/local/bin/wal", line 33, in 
> > sys.exit(load_entry_point('pywal==3.3.1', 'console_scripts', 'wal')())
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.11/dist-packages/pywal/**main**.py", line 208, in main
> > parse_args(parser)
> > File "/usr/local/lib/python3.11/dist-packages/pywal/**main**.py", line 163, in parse_args
> > colors_plain = colors.get(image_file, args.l, args.backend,
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.11/dist-packages/pywal/colors.py", line 144, in get
> > colors = getattr(backend, "get")(img, light)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.11/dist-packages/pywal/backends/wal.py", line 86, in get
> > colors = gen_colors(img)
> > ^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.11/dist-packages/pywal/backends/wal.py", line 41, in gen_colors
> > raw_colors = imagemagick(16 + i, img, magick_command)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.11/dist-packages/pywal/backends/wal.py", line 19, in imagemagick
> > return subprocess.check_output([*magick_command, img, *flags]).splitlines()
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
> > return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/lib/python3.11/subprocess.py", line 571, in run
> > raise CalledProcessError(retcode, process.args,
> > subprocess.CalledProcessError: Command '['convert', '/home/m/Pictures/wallpapers/edger_lucy_neon.jpg[0]', '-resize', '25%', '-colors', '16', '-unique-colors', 'txt:-']' returned non-zero exit status 1.

can you check if imagemagick is installed? if not install it

sudo apt-get --fix-missing install imagemagick

**Comment by Mathieux83** [comment]
nope isn't, after install and reboot 1st prob done thx

`

> ``
> ..[m@Coucou-C-Moi] - [~] - [Sat Dec 09, 01:54]
> ..[$] <()> wal -i /home/m/Pictures/wallpapers/edger_lucy_neon.jpg
> [I] image: Using image edger_lucy_neon.jpg.
> [I] colors: Generating a colorscheme.
> [I] colors: Using wal backend.
> [I] colors: Generation complete.
> [I] wallpaper: Set the new wallpaper.
> [I] sequences: Set terminal colors.
> 
>                                 
>                                 
> 
> [I] export: Exported all files.
> [I] export: Exported all user files.
> [I] reload: Reloaded environment.
> ..[m@Coucou-C-Moi] - [~] - [Sat Dec 09, 01:55]
> ..[$] <()> 

But still have config error at line 56 for $color2 again..

**Comment by JaKooLit** [comment]
aha... try to logout / login again..


all the colors are generated by pywal...

**Comment by DanielYuan123** [comment]
Thanks you all
