### ISSUE TITLE
Sorry i am reporting 2 issue.

### ISSUE THREAD

**Issue by Zeherjr** [JaKooLit/Debian-Hyprland#120]
### Before submitting report

[Kindly review the log files in Install-Logs directory. Some apps may have not installed properly.]

### Description

 1. My first issue is the waybar you setup for music and other sound that  is not working an i am getting  these emoji signs "????".
 2. My second issue is with chrome app when i use Hpyrland then i am not able to access my saved password.
### Steps to Reproduce (if applicable)

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots (if applicable)
![image](https://github.com/JaKooLit/Debian-Hyprland/assets/106311555/1ee53bdb-dde4-4fca-8717-e8a70fa34b88)

[If applicable, add screenshots to help explain your problem.]

### Proposed Solution (if applicable)

[If you have a specific solution in mind, describe it here. If not, you can skip this section.]

### Additional Information

[Add any other information about the issue or request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```


```

**Comment by JaKooLit** [comment]
[/home/ja/.config/kitty](https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#-waybar-cava-broken)

for the Chrome, I have no clue since I never like Chrome for being an electron based app.
