### ISSUE TITLE
Invalid dispatcher, requested "thunar" does not exist

### ISSUE THREAD

**Issue by DanielYuan123** [JaKooLit/Debian-Hyprland#13]
When I config the keybind setting, the error happens.I didn't modify the variable setting, but after I write the file the error just pop up. In fact, kitty can't be found either.
![image](https://github.com/JaKooLit/Debian-Hyprland/assets/94063653/fb202b2b-7cc5-4355-835a-91fb42071edf)![image](https://github.com/JaKooLit/Debian-Hyprland/assets/94063653/397bd68a-b0f2-442f-9d78-01ce2056f28d)

**Comment by JaKooLit** [comment]
**"When I config the keybind setting,"**

you have changed something... revert back

rules of changing settings, back up... if something happens, you can safely revert

**Comment by DanielYuan123** [comment]
Thanks
Fixed
