### ISSUE TITLE
[NEWBIE] Authentication failed at pokemon scripts/shz shell

### ISSUE THREAD

**Issue by Khoi1909** [JaKooLit/Debian-Hyprland#136]
It can not change the shell to shz and spamming authentication error. I don't figure out how to work it.
screenshot:
![Screenshot from 2024-08-04 19-43-49](https://github.com/user-attachments/assets/7990fd62-d6ba-4d27-b293-0a9006921294)

**Comment by JaKooLit** [comment]
TBH, I have never encountered this

Script does not alter any password related

**Comment by JaKooLit** [comment]
Closing as no reply from OP
