### ISSUE TITLE
Script no longer works on Ubuntu 24.04

### ISSUE THREAD

**Issue by unklebonehead** [JaKooLit/Debian-Hyprland#137]
Script no longer works on Ubuntu 24.04.

I do not know what changed because it was working just fine roughly a month ago as I had used it to install. Today I've tried on 2 different machines with fresh Ubuntu 24.04 installs. It runs through the installer as normal throws no errors. When logging in there is no Hyprland entry in GDM and trying the Hyprland command from tty gives "command not found".

What logs do you need if any?

**Comment by JaKooLit** [comment]
cd Ubuntu-Hyprland
./install-scripts/hyprland.sh

command not found just means hyprland is not installed

**Comment by unklebonehead** [comment]
NM, I'm a complete bonehead. 
I was in the wrong directory trying to install. Lol.
Sorry for any confusion.

**Comment by unklebonehead** [comment]
It works when Im not a bonehead.
