### ISSUE TITLE
copy / paste broken

### ISSUE THREAD

**Issue by outbackdingo** [JaKooLit/Debian-Hyprland#138]
seem mouse copy / paste is broken, i used to be able to double click on test, or drag to highlight, then swith to ay terminal and center click paste.... 

now i physically have to right click - copy then right click paste....

**Comment by JaKooLit** [comment]
Kindly complete the info

Distro, packages, etc etc

**Comment by JaKooLit** [comment]
incomplete info

**Comment by outbackdingo** [comment]
it affects Debian and Fedora, copy paste via mouse buttons is somehow disabled with your configuration, however it works fine on stock configuration. I believe its something in your hyprland config
