### ISSUE TITLE
can't install vmware, kernel-headers were not found for my version

### ISSUE THREAD

**Issue by ru4chmchp** [JaKooLit/Debian-Hyprland#139]
how can i install vmware, pls help me

**Comment by ru4chmchp** [comment]
![Screenshot_07-Aug_12-15-07_11517](https://github.com/user-attachments/assets/5813b9b7-4d61-4375-8141-d59522246d35)

**Comment by JaKooLit** [comment]
VMWARE and Virtual Box have a poor support

https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-will-it-work-on-a-vm-vmware-virtualbox-or-any-virtualization
