### ISSUE TITLE
Vulkan-ValidationLayers not  available in trixie repos

### ISSUE THREAD

**Issue by PerfMonk** [JaKooLit/Debian-Hyprland#14]
It's not found anymore.  I'm on SparkyLinux but the package isn't available.  I tried to compile from github and instructions at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.md   but once compiled instructions are not clear for the install or integration with hyprland.  I compiled it but haven't fount how to install it and I wonder what part of the installation should I restart to have integration with Vulkan.  And is it problematic not to have it at all ???

**Comment by JaKooLit** [comment]
dont worry about.. some packages may or may not needed nymore. This was the list of packages that was originally meant for bookworm.
