### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by daedaevibin** [JaKooLit/Debian-Hyprland#143]
no log files were provided. i simply can't log in to it. ALSO swww is NOT available in Ubuntu and HAS to be built from source using cargo which the installer did not do.

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/blob/Ubuntu-24.04-LTS/install-scripts/swww.sh


you dont have to log in to Hyprland to check log

you can use tty... or even gnome if you have installed..

no log means I cant debug and I cant help if not even a description of whats the issue....

this is not the right way to report



oh.... yes I am fully aware that its not if ubuntu repo... I created this script

**Comment by daedaevibin** [comment]
> https://github.com/JaKooLit/Debian-Hyprland/blob/Ubuntu-24.04-LTS/install-scripts/swww.sh
> 
> you dont have to log in to Hyprland to check log
> 
> you can use tty... or even gnome if you have installed..
> 
> no log means I cant debug and I cant help if not even a description of whats the issue....
> 
> this is not the right way to report
> 
> oh.... yes I am fully aware that its not if ubuntu repo... I created this script

Sorry, I meant to remove this earlier. I just realized a tutorial I was given was incorrect especially after a third party provided more specific information to my issues.

I did get it to work and do infact enjoy it very much. Thanks for creating it! :)

Maybe you can make one for Arch Linux as well? It is the most heinous and absolutely infuriating and painful process to get it to work. I have had absolutely nothing but zero luck in it.

**Comment by JaKooLit** [comment]
> > https://github.com/JaKooLit/Debian-Hyprland/blob/Ubuntu-24.04-LTS/install-scripts/swww.sh
> > you dont have to log in to Hyprland to check log
> > you can use tty... or even gnome if you have installed..
> > no log means I cant debug and I cant help if not even a description of whats the issue....
> > this is not the right way to report
> > oh.... yes I am fully aware that its not if ubuntu repo... I created this script
> 
> Sorry, I meant to remove this earlier. I just realized a tutorial I was given was incorrect especially after a third party provided more specific information to my issues.
> 
> I did get it to work and do infact enjoy it very much. Thanks for creating it! :)
> 
> Maybe you can make one for Arch Linux as well? It is the most heinous and absolutely infuriating and painful process to get it to work. I have had absolutely nothing but zero luck in it.

https://github.com/JaKooLit

I have for Arch, Fedora, OpenSuse, Ubuntu and of course Debian :)
Look at the pinned repos
