### ISSUE TITLE
Selecting FIle Window is Not Opening

### ISSUE THREAD

**Issue by mr-revoo** [JaKooLit/Debian-Hyprland#15]
When i go prompt to upload a file from my device the Selecting File Window is not opening and the browser window freezes

**Comment by JaKooLit** [comment]
? First off, I dont set to install any browser, so that could be browser issue.

2nd, script is only to install packages.



This is not an a complete OS its not the right place for you to ask such question

**Comment by mr-revoo** [comment]
there's sth i noticed it works on the normal gnome wdm but in hyprland it doesn't work

**Comment by JaKooLit** [comment]
what is your browser?

**Comment by mr-revoo** [comment]
brave

**Comment by mr-revoo** [comment]
i tried with opera and firefox and chrome and i faced the same issue

**Comment by JaKooLit** [comment]
did you install xdg desktop portal hyprland?

**Comment by JaKooLit** [comment]
did you reboot your system? after install?

**Comment by mr-revoo** [comment]
i think i didn't install it

**Comment by mr-revoo** [comment]
could you help me install it cause when it installs it shows me that 
![swappy-20231213-195114](https://github.com/JaKooLit/Debian-Hyprland/assets/115378793/f8b3d272-1380-4fbf-bb65-9592ca7e11d2)
