### ISSUE TITLE
[Bug]: CPU monitor won't render and Hint screen won't work

### ISSUE THREAD

**Issue by jasidok** [JaKooLit/Debian-Hyprland#155]
## Bug Report

I have looked through all the install files and I have searched and searched for a previous error of this type.

### Description

I literally don't understand what is happening. I completely reinstalled my entire OS. I am running Kali. I did a full wipe and minimal reinstall. then installed your script from the CLI without anything else. The SDDM really installed well and easily. But it installed with issues with Rofi. at firat nothing involving that or Yad would work. I reinsalled both programs and now they work fine. but the cpu thing in the waybar and the keyhint.sh thing. It will run if i click on the file or run it from a terminal. but not from they keybind or clicking on the hint button.

### Steps to Reproduce

1. Install.
2. attempt to use keyhint button

Screenshots
![Screenshot_05-Sep_10-51-16_21380](https://github.com/user-attachments/assets/7d9c9513-8953-4225-a9f5-ef659a4aec80)

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
└─[$] <> inxi -CGIsSMnr
System:
  Host: kali Kernel: 6.8.11-amd64 arch: x86_64 bits: 64
  Desktop: Hyprland v: 0.41.2 Distro: Kali GNU/Linux 2024.3 kali-rolling
Machine:
  Type: Laptop System: LENOVO product: 21J5S06N00 v: ThinkPad P14s Gen 3
    serial: <superuser required>
  Mobo: LENOVO model: 21J5S06N00 v: SDK0T76530 WIN
    serial: <superuser required> UEFI: LENOVO v: R23ET77W (1.53 )
    date: 05/29/2024
CPU:
  Info: 8-core model: AMD Ryzen 7 PRO 6850U with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 4 MiB
  Speed (MHz): avg: 1337 min/max: 400/4768 cores: 1: 1397 2: 400 3: 2982
    4: 400 5: 1857 6: 400 7: 1625 8: 400 9: 1540 10: 1953 11: 2769 12: 400
    13: 1793 14: 1562 15: 400 16: 1514
Graphics:
  Device-1: AMD Rembrandt [Radeon 680M] driver: amdgpu v: kernel
  Device-2: Bison Integrated RGB Camera driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 24.1.2 with: Xwayland v: 24.1.2
    compositor: Hyprland v: 0.41.2 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu
    resolution: 1920x1200~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.1.3-2 renderer: AMD
    Radeon Graphics (radeonsi rembrandt LLVM 17.0.6 DRM 3.57 6.8.11-amd64)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: eth0 state: down mac: fc:5c:ee:62:79:10
  Device-2: Qualcomm QCNFA765 Wireless Network Adapter driver: ath11k_pci
  IF: wlan0 state: up mac: 04:7b:cb:cf:7f:34
  IF-ID-1: docker0 state: down mac: 02:42:58:ed:96:ca
  IF-ID-2: wwan0 state: down mac: N/A
Sensors:
  System Temperatures: cpu: 59.0 C mobo: N/A gpu: amdgpu temp: 51.0 C
  Fan Speeds (rpm): fan-1: 0
Repos:
  Active apt repos in: /etc/apt/sources.list
    1: deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
    2: deb-src http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
Info:
  Memory: total: 12 GiB available: 11.45 GiB used: 4.6 GiB (40.1%)
  Processes: 304 Uptime: 49m Shell: Zsh inxi: 3.3.35

```

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by brockar** [comment]
Here with Debian Trixie (and nvidia) all works great except a line on configfile that i don't remember.
But the Hint helper doens't work and I don't know witch program is to try to run.

**Comment by JaKooLit** [comment]
> Here with Debian Trixie (and nvidia) all works great except a the render function at line 123 of the `UserSettings.conf`. But the Hint helper doens't work and I don't know witch program is to try to run.
> 
> Edit: I find that the first error is caused by the fact that hyprland in debian testing has version `0.41.2`
> 
> The original error (`Hint screen won't work`) is caused because the script `KeyHints.sh` gives the error `./KeyHints.sh: line 34: yad: command not found` This is caused bc
> 
> ```
> Package yad is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> ```
> 
> yad has been [removed](https://tracker.debian.org/pkg/yad) from Debian Testing.
> 
> One solution could be download from [here](https://packages.debian.org/sid/amd64/yad/download). (Idk if it is secure).
> 
> sorry for so many edits, I'm just learning this hyprland stuff and I don't understand the config that well.


That is why actually I have set another branch just for Debian and Ubuntu since the new from main stream KooL's Hyprland-dots, will give some error
https://github.com/JaKooLit/Hyprland-Dots


Anyway, im glad you figure it out...
Hyprland is good in error reporting. If error occurs, all we have to do is comment it out

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/issues/159

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#-waybar-cava-broken
