### ISSUE TITLE
[Bug]: Short description of the issue Bluetooth not opening

### ISSUE THREAD

**Issue by krtekam** [JaKooLit/Debian-Hyprland#158]
![Screenshot_11-Sep_12-34-28_32306](https://github.com/user-attachments/assets/fd31ec91-1209-418e-a6f9-7d4208798658)
i am new in linux i cant connect to bluetooth

**Comment by JaKooLit** [comment]
did you choose to install bluetooth during installation?


if not,

sudo apt install --reinstall -y bluez blueman

after that
sudo systemctl enable --now bluetooth.service

**Comment by krtekam** [comment]
thanks it worked
