### ISSUE TITLE
[Suggestion]   Option to disable the cycling border colors on the active window

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/Debian-Hyprland#16]
First, Thank you so much for doing this.   Amazing job getting it working so well with debian.    Up until know I've only been able to use arch for hyprland. 

I've been using it all day in a VM.  The constant changing of the border color in the active window (In the settings.conf) is (for me) quite distracting and made it harder to use the GUI.  

Not everyone may know where to go to disable it or how to disable it.   I suggest at the very least, put in a note in the documentation about it. 

Thanks

**Comment by JaKooLit** [comment]
there is a part about questions and answers and I also put the link of faq and tips

**Comment by JaKooLit** [comment]
![Screenshot_20231226_101215_GitHub.jpg](https://github.com/JaKooLit/Debian-Hyprland/assets/85185940/e5c6500f-e450-4b24-be9b-80d974ef7332)

![Screenshot_20231226_101133_GitHub.jpg](https://github.com/JaKooLit/Debian-Hyprland/assets/85185940/7b0cfdb8-b09c-4d1b-b5f3-e3fb164b3814)

**Comment by dwilliam62** [comment]
Yes I read over your FAQ and TIPs pages on your TIP page is has: 

If you have questions, or need help you can open issue on my github.

Since i was suggesting a code or documentation change I  thought it appropriate to put  it here. 
Also the rainbow borders script was covered but not the active window 'strobe' effect.

**Comment by JaKooLit** [comment]
that is already covered on hyprland wiki


anyway, message noted.

Ill do changes on readme and wiki
