### ISSUE TITLE
[Bug]: Ubuntu 24.04.1 LTS can not use the script

### ISSUE THREAD

**Issue by NUAAMETEOR** [JaKooLit/Debian-Hyprland#161]
### Before submitting report

This script is NOT intended for Ubuntu / Ubuntu Based. Please read the README for the correct link.

### Description
When I run ./install.sh，it shows error message above

### Screenshots
![image](https://github.com/user-attachments/assets/d6e7fd72-19e5-46cf-8ceb-3ae9e9c474a8)

**Comment by JaKooLit** [comment]
Its exactly what the error tells you and I even stated on the readme

https://github.com/JaKooLit/Debian-Hyprland?tab=readme-ov-file#note-ubuntu-hyprland-install-script-has-its-own-repo-now

here is the link
https://github.com/JaKooLit/Ubuntu-Hyprland

and pls go through readme 
https://github.com/JaKooLit/Ubuntu-Hyprland/tree/24.04

**Comment by NUAAMETEOR** [comment]
Thanks a lot,I mistake the branch

**Comment by NUAAMETEOR** [comment]
> Its exactly what the error tells you and I even stated on the readme
> 
> https://github.com/JaKooLit/Debian-Hyprland?tab=readme-ov-file#note-ubuntu-hyprland-install-script-has-its-own-repo-now
> 
> here is the link https://github.com/JaKooLit/Ubuntu-Hyprland
> 
> and pls go through readme https://github.com/JaKooLit/Ubuntu-Hyprland/tree/24.04

Thanks  a lot
