### ISSUE TITLE
Porting hyprland in Debian 12

### ISSUE THREAD

**Issue by Xdavius** [JaKooLit/Debian-Hyprland#163]
Hi

I'm working to port latest hyprland on Stable.
I use pacscripts from pacstall, but I need to add some packages and do some rework. Also pacscripts are outdated.

I also use homebrew for latest GCC. And pacscripts for libdrm and rust, and backports for latest pipewire.

I'm blocked trying to build xdg-desktop-portal-hyprland with an error I don't understand.

I also don't know if it's still needed... I'm searching in fact some help.

Well, maybe when I have finished, your dots may be compatible ?

Best regards.

**Comment by Xdavius** [comment]
Hi !

I have a now a possibility do build the latest version of hyprland.

In fact, I have used backports for pipewire (and there is also the latest wayland version available on backports but I have packaged it also. Pipewire is a big big baby. )

It was mostly a problem that I had to use 2 different versions of GCC.

And my previous work has been useful also because you need to rebuild mesa, libdrm libxinput, binden and you need the latest rust...

Well, I have all them all, also the xdg portal hyprland, who use an obsolete sdbus-cpp lib.... It's not possible ATM to share everything because they are still breaking bugs in pacstall so, it's also need to use my patched branch of pacstall ^^

I had also to update meson and cmake.

I don't know after upgrading all of this package if we can say that hyprland run on Debian Stable, using a lot of -git packages rebuilt from source 🤣

That was a challenge. But I think it's not something anyone have to do. It need too many knowledge to maintain everything in the time.

So... I have just stopped working on that ^^ I will upload the pacscripts on my git just for science :)

Have a nice weekend

**Comment by Xdavius** [comment]
For information, hyprland is now available on Trixie and Sid .

Still not the latest version including aquamarine, but not very old.

So, it's a good news.

**Comment by JaKooLit** [comment]
> For information, hyprland is now available on Trixie and Sid .
> 
> Still not the latest version including aquamarine, but not very old.
> 
> So, it's a good news.

fully aware. if you look at the script, it is installing from Debian repo

🙂
