### ISSUE TITLE
[Bug]: copy / paste with mouse not working

### ISSUE THREAD

**Issue by outbackdingo** [JaKooLit/Debian-Hyprland#167]
## Bug Report

in both Fedora and Debian, your configuration seems to disable mouse copy/paste capabilities. it affects Debian and Fedora, however it works fine on stock configuration. I believe its something in your hyprland config

**Comment by JaKooLit** [comment]
kindly be more specific when you said mouse copy paste capabilities

**Comment by outbackdingo** [comment]
i cannot right click highlight, middle click paste with the mouse buttons

**Comment by JaKooLit** [comment]
> i cannot right click highlight, middle click paste with the mouse buttons

you need to configure

super E User Settings
misc
middle click paste change to true

right click copy, not sure if kitty has that feature
https://sw.kovidgoyal.net/kitty/conf/

but by default, you can copy from kitty to clipboard by keyboard shortcut
ctrl shift c 
ctrl shift v for pasting

**Comment by outbackdingo** [comment]
why do i need to configure something that is plainly broken with your configs ? 
when it works clearly with the default config out of the box in everything, even kitty.?

youve done great work but copy/paste not being functional is kind of a deal breaker.

every DE ive used from KDE to Gnome to others copy/paste with mouse buttons clearly works, and does in fact
work by default with stock hyprland config. So i guess im curious why your unwilling to resov it?

yes, if i was a windows user :)
> but by default, you can copy from kitty to clipboard by keyboard shortcut
> ctrl shift c
> ctrl shift v for pasting

**Comment by JaKooLit** [comment]
https://wiki.hyprland.org/Configuring/Variables/#misc


broken? phew..... i myself dont use the middle click paste feature and lots of my  users dont like the middle click paste feature hence the decision for me to disable that feature


and dont say it is broken where you can simple just change a one line settings


and fyi, I have not set any disable copy or paste feature on kitty default

**Comment by outbackdingo** [comment]
ok, my bad wrong word, not broken, disabled, how do i re-enable it

**Comment by JaKooLit** [comment]
I just stated how to renable above

**Comment by outbackdingo** [comment]
i changed  middle_click_paste = true as you suggested i still cannot copy/paste from one application to another

**Comment by JaKooLit** [comment]
if you are copying / pasting from any electron based packages like chrome or vscode, then its electron issue...

I gave up on on these electron based apps, as it is just bound to break every update. Electron based apps is just shite

if any other apps, sry cant help, but since it is debian, im guessing its just old hyprland version since I just tried now on my system with most up to date hyprland and I dont have issue

perhaps some other debian users will chime in to it

**Comment by outbackdingo** [comment]
ok, so ive narrowed this down to vivaldi browser, firefox -> tilix and vice versa work fine
