### ISSUE TITLE
BLack Screen after installation

### ISSUE THREAD

**Issue by Xarilaos99** [JaKooLit/Debian-Hyprland#17]
Hi , i tried download hyprnland in kali linux following this video https://www.youtube.com/watch?v=CYHj9OCmujc.
However, after the installation, before booting up, I see this on my screen:

![IMG_20231228_193659__01](https://github.com/JaKooLit/Debian-Hyprland/assets/106752454/95284333-65f8-4906-983c-428506f2da57)

And when the setup is finished, I just get a black screen.
If you have any suggestions or recommendations, please feel free to share them.

**Comment by JaKooLit** [comment]
I need more info. Like installation logs. and system specs...

**Comment by JaKooLit** [comment]
Closing as no reply from user for long time
