### ISSUE TITLE
No option for Hyprland on Gnome Display Manager

### ISSUE THREAD

**Issue by nasapollo13** [JaKooLit/Debian-Hyprland#18]
https://www.youtube.com/watch?v=PMQf9gAt8FE&t

I watched this tutorial on how to install Hyprland and I followed the steps but around seven minutes in, it said to reboot the computer and on the login page click on the bottom right and select Hyprland, for me it only had Ubuntu and Ubuntu Wayland.

Is there a way to fix this?

**Comment by JaKooLit** [comment]
Sounds like the hyprland was not installed.

You can log-in to ubuntu and inside Debian-Hyprland folder, you will see alot of the install.logs in there.

Compress and send here.. or you can just attach all. Or you can verify yourself. Look for errors

**Comment by JaKooLit** [comment]
closing as user dont reply.
