### ISSUE TITLE
Will it works with Linux Mint/ Pop!OS/ KDE Neon

### ISSUE THREAD

**Issue by vuongtuha** [JaKooLit/Debian-Hyprland#19]
I just listed some Ubuntu-based distro but heavily changed main repo 
Or we just let users decide it later

**Comment by JaKooLit** [comment]
if they are 23.10 Based, then probably it will work..

I cannot guarantee it.....

If main repo is changed to newer repo, maybe it will work. However, as stated above, I cannot guarantee it.

**Comment by vuongtuha** [comment]
So that wont work anyway. I just checked, all of these 3 are based on Ubuntu LTS only.
Anyway thank you, it worked on my Sid machine! You can close this prob.
