### ISSUE TITLE
sddm Installation Menu Unresponsive to Arrow Key Inputs

### ISSUE THREAD

**Issue by roadsidev** [JaKooLit/Debian-Hyprland#2]
Hello,

Thank you for the great project. I've encountered an issue on two machines during the installation process.

Upon running `install.sh` and reaching the "`sddm`" installation, the selection menu for "gdm3" and "sddm" does not respond to arrow key navigation as expected. Instead, the terminal displays ANSI escape sequences for the arrow keys, halting the installation process. The only way out is using "ctrl + C".

**Steps to Reproduce:**

1. Run `install.sh`.
2. Wait until the script reaches the "`sddm`" installation step.
3. Attempt to navigate the menu using arrow keys.

**Expected Behavior:**
The arrow keys should navigate between the "gdm3" and "sddm" options.

**Actual Behavior:**
Arrow key presses result in displaying ANSI escape sequences, preventing menu navigation.

**Screenshots:**

![IMG_5558](https://github.com/JaKooLit/Debian-Hyprland/assets/6503047/2843a333-fb4b-465f-9866-58140a3c78f2)
![IMG_5559](https://github.com/JaKooLit/Debian-Hyprland/assets/6503047/399e689f-8438-4d50-8d96-f4d7fe56a2a0)

I'll look into this issue and submit a PR if I find a solution.

Thanks,
Chris

**Comment by roadsidev** [comment]
So here's what I did to fix it for now: I stopped the **sddm** setup with Ctrl + C, waited for the rest to install, then ran `sudo apt install sddm` and after that, I ran `sddm.sh`. That seemed to work!

**Comment by JaKooLit** [comment]
Thanks for this. I'll keep this issue open for now.... 

I have also stated on the readme.

For now, highly advised not install SDDM if GDM is already installed.

**Comment by catluvies** [comment]
very good

**Comment by JaKooLit** [comment]
> So here's what I did to fix it for now: I stopped the **sddm** setup with Ctrl + C, waited for the rest to install, then ran `sudo apt install sddm` and after that, I ran `sddm.sh`. That seemed to work!

just a quick question. Debian or Ubuntu 

In Debian, when you ran apt install sddm, it is downloads lots of plasma packages

thats why if you check the sddm.sh, I append --no-install-recommends

I havent tested in Ubuntu but during my test, I didnt install sddm as it has already GDM

**Comment by roadsidev** [comment]
> > So here's what I did to fix it for now: I stopped the **sddm** setup with Ctrl + C, waited for the rest to install, then ran `sudo apt install sddm` and after that, I ran `sddm.sh`. That seemed to work!
> 
> just a quick question. Debian or Ubuntu
> 
> In Debian, when you ran apt install sddm, it is downloads lots of plasma packages
> 
> thats why if you check the sddm.sh, I append --no-install-recommends
> 
> I havent tested in Ubuntu but during my test, I didnt install sddm as it has already GDM

I followed these steps on Ubuntu 23.10, using the server image. After a clean installation, I modified the sources.list as outlined in the instructions and then executed the script.

**Comment by PerfMonk** [comment]
Are all those zillions of plasma packages really needed for SDDM ???? Il looks it want to install whole plasma ...
I did not install sddm and start Hyprland from console instead.  In  Arch you have a package for sddm qt and another one for sddm gtk but it doesn't bring all those libraries.  Can it be an error from the sddm debian packager ???

**Comment by JaKooLit** [comment]
> Are all those zillions of plasma packages really needed for SDDM ???? Il looks it want to install whole plasma ...
> I did not install sddm and start Hyprland from console instead.  In  Arch you have a package for sddm qt and another one for sddm gtk but it doesn't bring all those libraries.  Can it be an error from the sddm debian packager ???
> 

check my script first !!!!. I have set to install no-recommends...


and if you install on a server none DE type debian install, needed all those qt controls since sddm is only --no-recommends

**Comment by rivando-al-rasyid** [comment]
i have that to fisrt time i use script 
bu i nstall first after that it work

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/0be860cbab6afee67e8d9eece861974a85a4c311

I can now close this as this commit should prevent users to install sddm

**Comment by mamtheus109878** [comment]
Installing on Asus ROG laptops? (y/n): y
  In this question here I ended up making a mistake, will anything happen?

**Comment by JaKooLit** [comment]
> Installing on Asus ROG laptops? (y/n): y In this question here I ended up making a mistake, will anything happen?

yes your system will turn to ASUS ROG 

🤣


Joke


will just install ASUSCTL and SUPERGFXCTL
you can review what the script does here
https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/rog.sh

**Comment by mamtheus109878** [comment]
I apologize and I'm new to using Linux

**Comment by JaKooLit** [comment]
https://raw.githubusercontent.com/JaKooLit/Debian-Hyprland/main/Debian-Install.png

sure but I also explained on the readme
