### ISSUE TITLE
Switching to Other DE's (that uses Wayland) on login launches Hyprland instead

### ISSUE THREAD

**Issue by SuchWowEl** [JaKooLit/Debian-Hyprland#20]
I run Debian Sid and have noticed that when I tried switching to other DE's (for example, KDE Wayland), it launches Hyprland. The same happens when I login to Gnome (Wayland).

**Comment by JaKooLit** [comment]
wow SID? hmmm 

anyway, you can try deleting the ~/.zprofile

or move it your documents

**Comment by SuchWowEl** [comment]
Yep, that works. Thank you! However waybar and mako (and probably there are more to mention) still gets launched. I'm not sure if this behavior is expected, but can I exclude these from getting launched if I'm on other DE's? This will be a nice feature if implemented, imo.

**Comment by JaKooLit** [comment]
Honestly, there is something seriously wrong with that.. the waybar and other hyprland related apps are being called on hyprland configuration.

I have a fedora with gnome and I never have that issue.

so something is starting hyprland....and I dont know

**Comment by SuchWowEl** [comment]
Neither do I... In any case, there was something wrong with my installation. I've failed to mention earlier that dependencies libavcodec-dev and libavformat-dev have failed to install on my machine (a package fails to resolve dependencies). This could be why Hyprland wasn't behaving as expected.

**Comment by JaKooLit** [comment]
ok thanks..

Inside the Debian-Hyprland folder, it creates a logs.

Can you attach here the logs?

**Comment by JaKooLit** [comment]
I have just install SID with gnome, install Hyprland on it using the script,

Have no issues encounter.

Tried running Debian-Gnome after install Hyprland,

anything Hyprland related like waybar or so did not start!
