### ISSUE TITLE
Error setting value <$color2> for field <decoration:col.shadow>, stoll

### ISSUE THREAD

**Issue by Niladrithub** [JaKooLit/Debian-Hyprland#22]
Config error at line 59 (~/.config/hypr/UserConfigs/UserSettings.conf): Error setting value <$color2> for field <decoration:col.shadow>, stoll.
Hyprland may not work correctly.

I logged in to my desktop and found this red error at the top of the screen and my screen was blank, no Waybar. Except this, everything is okay. Everything seems to work fine, except for the waybar.

- Linux Distro: Ubuntu 23.10
- Linux Version, output of `uname -a`: Linux 6.5.0-14-generic x86_64 x86_64 x86_64 GNU/Linux
- Hyprland Version: Tag: v0.32.3
- Installation Environment: [ On The Main Hardware]
[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by Niladrithub** [comment]
It got alright, after reinstalled hyprland again.

**Comment by JaKooLit** [comment]
ok cool thanks... seems like pywal was not installed / started first time
