### ISSUE TITLE
Ubuntu 23.04 - Hyprland not showing in login

### ISSUE THREAD

**Issue by Koteyo** [JaKooLit/Debian-Hyprland#25]
Hi, I followed the instructions in the video (https://youtu.be/PMQf9gAt8FE?si=EWIBsGe7dKRwshQy) Once I restarted the computer, at the Login screen Hyprland was not present in the selection, by logging in with Ubuntu I notice that the installation changed the Ubuntu installation files. I fortunately have a backup made with Deja-dup restorable but would like to avoid having to restore it. 

Is there ANY WAY to completely remove all the changes made by following the procedure? I would like to go back to my Ubuntu installation to before the attempt to install Hyprland.

**Comment by JaKooLit** [comment]
review the readme... I especifically mentioned only for 23.10
