### ISSUE TITLE
[Bug]: Script executed but Hyperland option not appears

### ISSUE THREAD

**Issue by renanmachad** [JaKooLit/Debian-Hyprland#26]
### Script executed but Hyperland option not appears

Hello, i make the steps necessary to install the Hyperland, 
editing my sourcelist file, choosing the options and more.
But in login page of the system, the option to Ubuntu on Hyperland not appears, just Ubuntu and OPenBox.
The apps that install.sh install are installed successfully, like ZSH and others things.

### Steps to Reproduce

1. Execute the script install.sh following the recommendations

[What actually happened?]

### Screenshots
![image](https://github.com/JaKooLit/Debian-Hyprland/assets/75550396/81607662-419d-46c8-bc5f-952e1df41c41)

### Environment
I do not have NVIDIA GPU on my pc, just a AMD RYZEN with integrated processor.

**Comment by JaKooLit** [comment]
its quite possible that hyprland was not installed. kindly attach or review the install logs

**Comment by renanmachad** [comment]
I Will share my logs here

**Comment by renanmachad** [comment]
[Install-Logs.zip](https://github.com/JaKooLit/Debian-Hyprland/files/14017881/Install-Logs.zip)
This is my folders for logs, i will read too, if anyone can help me  i will very appreciated ;D.

**Comment by renanmachad** [comment]
This is my Hyperland log,
```
mkdir -p /usr/local/share/hyprland
cp ./assets/wall_* /usr/local/share/hyprland
mkdir -p /usr/local/share/xdg-desktop-portal
cp ./assets/hyprland-portals.conf /usr/local/share/xdg-desktop-portal
mkdir -p /usr/local/share/man/man1
install -m644 ./docs/*.1 /usr/local/share/man/man1
mkdir -p /usr/local/lib/
cp ./subprojects/wlroots/build/libwlroots.so.12032 /usr/local/lib/
make installheaders
make[1]: Entering directory '/home/renan/Debian-Hyprland/Hyprland'
mkdir -p /usr/local/include/hyprland
mkdir -p /usr/local/include/hyprland/protocols
mkdir -p /usr/local/include/hyprland/wlroots
mkdir -p /usr/local/share/pkgconfig
find src -name '*.h*' -print0 | cpio --quiet -0dump /usr/local/include/hyprland
cd subprojects/wlroots/include && find . -name '*.h*' -print0 | cpio --quiet -0dump /usr/local/include/hyprland/wlroots && cd ../../..
cd subprojects/wlroots/build/include && find . -name '*.h*' -print0 | cpio --quiet -0dump /usr/local/include/hyprland/wlroots && cd ../../../..
cp ./protocols/*-protocol.h /usr/local/include/hyprland/protocols
cp ./build/hyprland.pc /usr/local/share/pkgconfig
if [ -d /usr/share/pkgconfig ]; then cp ./build/hyprland.pc /usr/share/pkgconfig 2>/dev/null || true; fi
chmod -R 755 /usr/local/include/hyprland
chmod 755 /usr/local/share/pkgconfig
make[1]: Leaving directory '/home/renan/Debian-Hyprland/Hyprland'
[32m[OK][m Hyprland installed successfully.
```

**Comment by renanmachad** [comment]
If my ubuntu use Wayland or XFCE have some difference in the process? How i can discover this?

**Comment by milesdredd** [comment]
same issue with my laptop, no hyperland option !!

**Comment by renanmachad** [comment]
yes, i not found a solution for this, and in script installation i not found a error message that be clear about the motivation of this error

**Comment by milesdredd** [comment]
> yes, i not found a solution for this, and in script installation i not found a error message that be clear about the motivation of this error

Because i m on LTS ubuntu , i wont run ig 😶‍🌫️ but why this

**Comment by JaKooLit** [comment]
> > yes, i not found a solution for this, and in script installation i not found a error message that be clear about the motivation of this error
> 
> Because i m on LTS ubuntu , i wont run ig 😶‍🌫️ but why this

review the readme.

I stated in there the reason why it wont work on LTS versions

**Comment by renanmachad** [comment]
fuck, the my ubuntu version is 23.0 so its not work rigth?

**Comment by Muhammad-Abuzor** [comment]
I am having the same problem. Any solutions yet?

**Comment by renanmachad** [comment]
> I am having the same problem. Any solutions yet? My Ubuntu version is 23.10 btw

I not found

**Comment by JaKooLit** [comment]
any status of this?

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/c19b76fb01e63dd5b2eec26e772a20d5508327e9

I have updated to latest Hyprland v0.39.1 

however, it does not work with 23.10 anymore. Will work on Ubuntu 24.04 LTS though

**Comment by Kane-dylan** [comment]
I have 24.04 lts running also can see the hypeland option in gdm login screen but major issue can't pass through the login screen . Have also tried tty login that also failed.
