### ISSUE TITLE
Key bindings not working

### ISSUE THREAD

**Issue by Adi1912-pro** [JaKooLit/Debian-Hyprland#33]
I have installed the hyprland (on UBUNTU 23.1) as per the instructions and after successful installation some keybindings do not work, unable to edit keybindings and also app launcher doesn't show up.

Some of the key bindings that do not work are:-

1. Super key + W
2. super key (stand alone)
3. super key + E
4. super key + D

**Comment by JaKooLit** [comment]
quite possibly rofi-wayland was not installed properly

**Comment by Adi1912-pro** [comment]
Is there any solution to resolve this issue ?

**Comment by JaKooLit** [comment]
have you tried re-running the script?

**Comment by Adi1912-pro** [comment]
I have reinstalled hyperland multiple times by formating the disk and then installed it on fresh ubuntu 23.1. But same error every time.

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/c19b76fb01e63dd5b2eec26e772a20d5508327e9

I have updated to latest Hyprland v0.39.1 

however, it does not work with 23.10 anymore. Will work on Ubuntu 24.04 LTS though

**Comment by l3ifk** [comment]
I just installed hyprland with this script in Ubuntu 24.04LTS and have the same issue... is there a way to install missing packages manually?

**Comment by JaKooLit** [comment]
did you use the ubuntu branch?

**Comment by l3ifk** [comment]
yes just like it's mentioned in the docs

**Comment by JaKooLit** [comment]
> yes just like it's mentioned in the docs

just to be clear, you logout and then choose Hyprland on login manager? Just covering basic here since Ive seen on occasion they start Hyprland on tty while running Ubuntu-Gnome

**Comment by l3ifk** [comment]
Yeah of course. I also did an update and reboot. I can't close windows other than the key binding window and cant even open the app launcher along with many other bindings

**Comment by JaKooLit** [comment]
can you attach a screeenshot?

**Comment by l3ifk** [comment]
I'm sorry if it is obvious, but what do you want a screenshot of?

**Comment by l3ifk** [comment]
I uninstalled hyprland with `sudo make uninstall` inside the 'Hyprland' folder and then rerun the script. Now it works better but still no keybinds... For example touchpad gestures for Workspace switching work now and I can resize windows, which was not possible before. Still not App Launcher oder Wallpaper choosing etc.

**Comment by JaKooLit** [comment]
> I'm sorry if it is obvious, but what do you want a screenshot of?

your whole screen...

im just trying to grasp the situation

**Comment by l3ifk** [comment]
![Screenshot_27-May_22-47-33_4496](https://github.com/JaKooLit/Debian-Hyprland/assets/100339546/f2d8eb12-56e4-4bd0-8332-149abf657560)

**Comment by JaKooLit** [comment]
open kitty (Super enter) and then type this

rofi -show drun -modi drun,filebrowser,run,window


any output? error?

**Comment by l3ifk** [comment]
okay thanks

**Comment by JaKooLit** [comment]
> Ah I see the problem is there the package is not available and that's why the script couldn't install it `E: Unable to locate package rofi-wayland`

you need to manually compile it...

Debian / Ubuntu dont have it in their repo

https://github.com/lbonn/rofi

**Comment by l3ifk** [comment]
sorry to bother you, rofi works now thank you for your help! I just have a question what part is responsible for the wallpaper selector since it still is unavailable and I couldn't figure out which command would launch it

**Comment by JaKooLit** [comment]
kindly review contents of directories inside

~/.config/hypr

I have also created a small wiki

https://github.com/JaKooLit/Hyprland-Dots/wiki

in which this link is in the readme
