### ISSUE TITLE
[Bug]: Black screen after trying to login (Ubuntu 23.10 on a Virtual Box Machine)

### ISSUE THREAD

**Issue by rabb1tl0ka** [JaKooLit/Debian-Hyprland#35]
### Description

I installed Ubuntu 23.10 on a Virtual Box Machine on a Ubuntu 20.04.6 LTS machine as a host.
The virtual machine had 3D acceleration on.

![Screenshot from 2024-02-10 11-35-41](https://github.com/JaKooLit/Debian-Hyprland/assets/92385648/aa90a264-8bb1-4027-88f2-5e1a5afc900b)

I followed the steps to install from source and then, after the installation was successful, the login via Hyprland just gives me a black screen.

### Steps to Reproduce

1. I followed the steps to install
2. edited the /etc/apt/sources.list
3. Do you have nvidia - N
4. Configure bluetooth - Y
5. Install Thunar - Y
6. Install and configure SDDM - N
7. Install XDG-DESKTOP-PORTAL-HYPRLAND - Y
8. Install zsh & oh-my-zsh plus pokemon - Y
9. Install sway-lock - Y
10. Install nwg-look - Y
11. Install on Asus Rog - N
12. Install dot files - N
13. After it was done, I tried to login by choosing the Hyprland option (botton right corner)
14. Black screen

### Expected Behavior

I expected it to work? :100: 

### Actual Behavior

Just a black screen. No cursor.

### Screenshots

No need to add a screenshot since it was a just an entire black screen.

### Environment

**Host Machine**
OS: Ubuntu 20.04.6 LTS x86_64 
Host: 20UN002GPG ThinkPad X1 Nano Gen 1 
Kernel: 5.15.0-92-generic 
Uptime: 10 mins 
Packages: 2910 (dpkg), 1 (brew), 11 (flatpak), 39 (snap)
Shell: bash 5.0.17 
Resolution: 2160x1350 
DE: GNOME 
WM: Mutter 
WM Theme: Orchis-Red-Dark 
Theme: Orchis-Red-Dark-Compact [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i5-1130G7 (8) @ 4.000GHz 
GPU: Intel Device 9a40 
Memory: 5446MiB / 15709MiB 

**Virtual Box Machine Spec:**
OS: Ubuntu 23.10 x86_64
Host: Virtual Box 1.2
Kernel: 6.5.0-17-generic
Shell: zsh 5.9
Resolution: 1280 x 800
DE: GNOME 45.2
WM: Mutter
CPI: 11th Gen Intel i5-1130G7
GPU: 00:02.0 VMware SVGA II Adapter
Memory: 3906Mib

**Comment by JaKooLit** [comment]
thank you for your well detailed report.

tbh, I have not used vbox so I have no clue. I am using qemu-kvm

I will just leave this open so in case some guys might have same experience and be able to help

**Comment by rabb1tl0ka** [comment]
> tbh, I have not used vbox so I have no clue. I am using qemu-kvm
I tried it myself and it does work on qemu-kvm on my machine too :+1: 

It's definitely something with the Virtual Box system somehow that gets in the way...

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/c19b76fb01e63dd5b2eec26e772a20d5508327e9

updated to newer hyprland. However, it does not work with 23.10 anymore
