### ISSUE TITLE
Visual Code doesn't load

### ISSUE THREAD

**Issue by HIXETA** [JaKooLit/Debian-Hyprland#36]
Hi, 

love your work. 

I recently discovered that whenever I try to run Visual Studio Code in Hyprland environment, Hyprland automatically logs me out and I have to re-enter my password and login back. I downloaded Visual Studio from the Ubuntu Store (snap), issue doesn't occur in Gnome or KDE it's just with Hyprland. 

Any ideas what causes this and how to fix it. I can use other editors like nvim, the issue only occurs with Visual Code. 

Any help would be appreciated.

**Comment by JaKooLit** [comment]
electron base... try to disable gpu acceleration on vscode...

**Comment by JaKooLit** [comment]
Closing as I assumed he found the fix

**Comment by dwilliam62** [comment]
Snap package is outdated  "classic" packaging.   That would not start in ubuntu 24.10    I removed that and installed the deb package on ubuntu 24.10 and it works fine     replied to OP on discord
