### ISSUE TITLE
Swww buil fails on ubuntu 23.10

### ISSUE THREAD

**Issue by qxprakash** [JaKooLit/Debian-Hyprland#37]
### Description

swww build fails

### Steps to Reproduce

run the install script on ubuntu 23.10

- Linux Distro: ubuntu 23.10
- Linux Version, output of `uname -a` :Linux prakash-REV-1-0 6.5.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 14:17:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3).
Tag: v0.32.3

- Installation Environment: main hardware 
- Other info: 1920*1080 

### logs

   Compiling time-macros v0.2.16
error: failed to run custom build command for `utils v0.8.2-master (/home/prakash/Downloads/swww/utils)`

Caused by:
  process didn't exit successfully: `/home/prakash/Downloads/swww/target/release/build/utils-122dfc20d02ff268/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBLZ4_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBLZ4_STATIC
  cargo:rerun-if-env-changed=LIBLZ4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at utils/build.rs:5:10:
  called `Result::unwrap()` on an `Err` value: 
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags liblz4 liblz4 >= 1.8

  The system library `liblz4` required by crate `utils` was not found.
  The file `liblz4.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `liblz4.pc`.

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by geromahony** [comment]
I was just coming here to share my experience which was the same issue but on Debian. I got around this by installing `liblz4-dev` and re-running the `swww.sh` installer script.

Another issue that I had which may be relevant for the Ubuntu install also was that `ngw-look` failed to install because the required `go` tool chain was missing from the packages repo. I got around this by deleting the `nwg-look` folder the install created and modifying this line here:
https://github.com/JaKooLit/Debian-Hyprland/blob/e32b628212eb87d1004144dec217da01ef691fd7/install-scripts/nwg-look.sh#L44

to be:
`if git clone https://github.com/nwg-piotr/nwg-look.git --branch v0.2.6 --single-branch; then` which requires `go` `1.21` not `1.22`, and then re-running the `nwg-look.sh` installer script.

I hope this helps!

**Comment by neop26** [comment]
> I was just coming here to share my experience which was the same issue but on Debian. I got around this by installing `liblz4-dev` and re-running the `swww.sh` installer script.
> 

Managed to get swww issue fixed because of this. Many thanks !

**Comment by Anhdao153** [comment]
@geromahony I have the same issue as you; I'm using Kali Linux. Where can I change the required Golang version? Which file does it stay in? Thanks

**Comment by geromahony** [comment]
> @geromahony I have the same issue as you; I'm using Kali Linux. Where can I change the required Golang version? Which file does it stay in? Thanks

Hi @Anhdao153 I just changed line 44 in `nwg-look.sh` which you will find in the install-scripts directory as described above.

That will build `nwg-look v0.2.6` which uses `go 1.21`:
https://github.com/nwg-piotr/nwg-look/blob/v0.2.6/go.mod

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/090a76e99fc61fcd5a93e081bffef660c96643ad
