### ISSUE TITLE
[Bug]: Linux Mint 21.3 there's nothing related to deb-src in sources.list 

### ISSUE THREAD

**Issue by Twig6943** [JaKooLit/Debian-Hyprland#38]
Title.
![image](https://github.com/JaKooLit/Debian-Hyprland/assets/119701717/5fc99473-a389-416a-9eda-7e8693c358f0)

**Comment by JaKooLit** [comment]
Linux mint are based on Old Ubuntu and Debian if I remember it correctly.


It wont work..

Although, I have to be honest, been long time since I have used mint

**Comment by Twig6943** [comment]
Are there any plans on adding linux mint support?

**Comment by JaKooLit** [comment]
> Are there any plans on adding linux mint support?

atm no..

reason being is that mint have old packages and hyprland needed newer packages
