### ISSUE TITLE
[Bug]: After installation, i get a black screen

### ISSUE THREAD

**Issue by BakrAsskali** [JaKooLit/Debian-Hyprland#39]
### Description

After installation i get i black screen with a toast saying:
Config error at line 59 (/home/{user}/.config/UserConfigs/UserSetting.conf): Error setting value for field <decoration;col.shadow>. stoll Hyprland may not work correctly.

All the apps still work i just dont see my dektop
### Steps to Reproduce

Install hyprland on latest ubuntu.

### Expected Behavior

Desktop to show up

### Actual Behavior

No desktop just a black screen

### Screenshots

no need for a screenshot

### Environment

- Linux Distro: ubuntu 23.10
- Linux Version, output of `uname -a`: 6.5.0-25-generic #25-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 14:58:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`:Hyprland, built from branch HEAD at commit 9afdd61adeaf413afbe853dbc5fdf6853c8bde21  (props: bump ver to 0.32.3).
Tag: v0.32.3

flags: (if any)
- Installation Environment: main hardware
- Other info: 1920:1080

**Comment by JaKooLit** [comment]
probably pywal is not installed properly.

inside Debian-Hyprland folder it creates install-logs folder.

attach here the install log of pywal

**Comment by BakrAsskali** [comment]
thank you for the help, i fixed it, i jest needed to add the pywal file at the end of the source line in the configs
