### ISSUE TITLE
[Feature Request]: What should I need to upgrade newest Hyprland 0.37

### ISSUE THREAD

**Issue by vuongtuha** [JaKooLit/Debian-Hyprland#40]
### Description

I'm on Sid, and I can found this 
libdrm2:
  Installed: 2.4.120-2
  Candidate: 2.4.120-2
  Version table:
 *** 2.4.120-2 500
        500 http://deb.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
I wanna upgrade to newest version or even git. But I'm not sure what component I need more

### Use Case
ALso I noticed that flatpak app dont follow my theme settings. I assume this's bcoz I lack of xdg-desktop-portal-hyprland

systemctl --user status xdg-desktop-portal-hyprland   10:59:35
Unit xdg-desktop-portal-hyprland.service could not be found.

I just wanna make sure that new version work with libdrm 2.4.120. Just tell me from your exp on other distro.

**Comment by vuongtuha** [comment]
![2024-03-17_21-09](https://github.com/JaKooLit/Debian-Hyprland/assets/70053986/7549ef6b-739c-45b7-9880-d59f5b472ddb)
There are 2 things I need to manual install:
* hyprland (not much additional dependencies)
* hyprcursor : depend libzip-dev libtomlplusplus-dev
Then I install full Hyprland from source file ( around 200MB). After that, I install xdg-desktop-portal-hyprland (dpend ibgbm-dev, libsdbus-c++-dev). At the 1st reboot, I was welcomed by fullscreen red-alert errors. Most of them told me that all lines starting with dash (#) are not accepted. Remove all of them are hassle
Hehe now I need to fix your config. But everything else is working fine. Forget that I temporary disable error in hyprland.conf

**Comment by JaKooLit** [comment]
great job.. thanks

I couldnt update the Debian-Hyprland install script because I forgot to bring My ssd with Debian... next month once I arrived home, ill update

however, I will add in the development for the newest hyprland and will post on my yt or discord for testing.

I will have to rely on you guys for testing since I cant test now

**Comment by JaKooLit** [comment]
For Some reason, I cant update to v0.37... on my test, it keeps complaining about libdrm not having  is old v

But, I have already that the latest libdrm....

annoying

**Comment by vuongtuha** [comment]
You can try libdrm-dev. Today i tried v39.1 from tarball. 
And workspace-indicator#pacman-style disappeared in my waybar. I checked module still existing, but now i'm lost. So sad!

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/25f35e166507b444e81f278c5a8143f9bdcf2071

its ok now :)

**Comment by vuongtuha** [comment]
Idk if you get the same issue or not, after upgrading to 0.39 
my waybar can't show any workspaces list at all. I tried most styles hyprland/workspaces. hyprctl workspaces list all active workspaces. But it's not visible on waybar anymore. 
Idk what i messed up =)

**Comment by JaKooLit** [comment]
> Idk if you get the same issue or not, after upgrading to 0.39 my waybar can't show any workspaces list at all. I tried most styles hyprland/workspaces. hyprctl workspaces list all active workspaces. But it's not visible on waybar anymore.
> 
> ![2024-04-30_18-53](https://private-user-images.githubusercontent.com/70053986/326793255-86003587-56db-4eb3-b6c9-0e8d3c6a3af2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODcwODEsIm5iZiI6MTcxNDQ4Njc4MSwicGF0aCI6Ii83MDA1Mzk4Ni8zMjY3OTMyNTUtODYwMDM1ODctNTZkYi00ZWIzLWI2YzktMGU4ZDNjNmEzYWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE0MTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMjVmYmNiOTM2MjExMWYyMjA5ZjkxMTFlZmIzZDQzNmY2MjczYzgxNjI2ODllOWE4YjkzOTQ5NzhkZDg4NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fkxbH2TyaWwhhqsPYsfz5GRx5ZY_KN38Sk3jI2HABlA)
> 
> Idk what i messed up =)

all is working on my system including waybar
![Screenshot_30-Apr_23-20-28_3094](https://github.com/JaKooLit/Debian-Hyprland/assets/85185940/2ec8ca31-91b7-4af9-9e2b-f9531440684d)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/c19b76fb01e63dd5b2eec26e772a20d5508327e9

**Comment by vuongtuha** [comment]
Closed, just wanna tell you i'm fine with git version. Also i was not mad, just 1 day cannot realized what workspace i'm currently working 
![2024-05-01_13-58](https://github.com/JaKooLit/Debian-Hyprland/assets/70053986/049f723b-fe93-44ae-8324-2e5387d5db3c)

**Comment by JaKooLit** [comment]
> Closed, just wanna tell you i'm fine with git version. Also i was not mad, just 1 day cannot realized what workspace i'm currently working 
> ![2024-05-01_13-58](https://github.com/JaKooLit/Debian-Hyprland/assets/70053986/049f723b-fe93-44ae-8324-2e5387d5db3c)
> 

didnt even thought about you being mad 😀
