### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by 0xIftekhar443** [JaKooLit/Debian-Hyprland#41]
vulkan-validationlayers failed to install

How can I fix it , Is it effect when I use Hyprland? I'm installing it on kali linux

also I have uncommented the #deb-src

**Comment by vuongtuha** [comment]
Don't uncomment #deb-src from main repo debian
deb-src http://deb.debian.org/debian/ testing main contrib non-free non-free-firmware
assume you're on Kali
