### ISSUE TITLE
Swww - Installing on Ubuntu 23.10 missing dependency

### ISSUE THREAD

**Issue by Djang0** [JaKooLit/Debian-Hyprland#42]
while installing on Ubuntu 23.10, liblz4 is missing see here for installing: https://github.com/lz4/lz4 . This avoid swww to be installed properly.

**Comment by JaKooLit** [comment]
I know lots of issues on this project. Unfortunately, I dont have with me my debian/ubuntu hyprland ssd (I forgot). So I will find and fix issues, depencies once Im at home by mid to end of this month

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/090a76e99fc61fcd5a93e081bffef660c96643ad
