### ISSUE TITLE
Non-native apps do not render

### ISSUE THREAD

**Issue by arghunter** [JaKooLit/Debian-Hyprland#6]
The installation works fine, but when I install apps such as discord and chromium where show up unfilled rectangles. I used the v1 script from the original version on my laptop and it worked fine. I am now trying the v2 version on my desktop and this happens. After first seeing the issue, i deleted the partition and tried again, however the issue persists. 

![image](https://github.com/JaKooLit/Debian-Hyprland/assets/91099806/7eb7158e-729d-41b7-ae40-f4180a060eea)

**Comment by arghunter** [comment]
Also, I'm on ubuntu

**Comment by arghunter** [comment]
vscode works, discord and chromium break

**Comment by arghunter** [comment]
I ran the version of the script that I used on my laptop, but the issue persists.  I also tried using the dotfiles from my laptops, but the issue persisted

**Comment by JaKooLit** [comment]
its not about v1 or v2, that is just electron apps have a weird behavaiour on wayland.....


have a read through here, this should help you

https://wiki.archlinux.org/title/Wayland#Electron

**Comment by arghunter** [comment]
Ok, thank you.
