### ISSUE TITLE
hyprland won't start

### ISSUE THREAD

**Issue by damianmg9** [JaKooLit/Debian-Hyprland#7]
(Using Ubuntu 23.10)
I installed everything I needed just to try if it worked on a vm before installing on my real system but when I select hyprland and log in it turns into a black screen and sends me back to the log-in screen, in case it's a question i'm using gdm, not sddm.

Note: I checked the logs and I only get one error, the package libjpeg62-turbo-dev won't install, I tried installing manually and I couldn't find it either so I tried installing libjpeg62-dev (I chose that one because it had a similar name I don't know the differences between them) and runing the install again but i't won't work either, any help is apreciated.

**Comment by JaKooLit** [comment]
on Debian-Hyprland folder


cd Hyprland
git pull
make all 
sudo make install


thats just making sure that Hyprland is compiled....

**Comment by damianmg9** [comment]
Followed these steps, same error

**Comment by JaKooLit** [comment]
> Followed these steps, same error

what is the error? Is hyprland compiled properly?

**Comment by damianmg9** [comment]
when I search error in the hyprland log I get this:

   drm-backend     : YES
    x11-backend     : YES
    libinput-backend: YES
    xwayland        : YES
    gles2-renderer  : YES
    vulkan-renderer : NO
    gbm-allocator   : YES
    session         : YES
    xcb-errors      : NO
    egl             : YES
    libliftoff      : YES

And appart from that the libjpeg62-turbo-dev which is not avialible in the dependencies which I told you earlier

**Comment by JaKooLit** [comment]
closed.. it turns out its a VM.

if installing on a VM. Ensure 3d acceleration is enabled. Bear in mind, performance of hyprland on a VM is crap
