### ISSUE TITLE
wlr_backend_autocreate() failed!

### ISSUE THREAD

**Issue by Moorocks** [JaKooLit/Debian-Hyprland#70]
### Description
My nvidia drivers were not getting detected, however i went ahead and installed hyprland. But once my vm restarted, I can see that hyprland was not installed correclty. so when i tried to run the command Hyprland, it threw me error.

### Steps to Reproduce

1. sudo nano /etc/apt/sources.list -- remove the comments
2. sudo apt update && sudo apt upgrade -y 
3. lspci | grep -i vga # did not get nvidia driver
4. 
![image](https://github.com/JaKooLit/Debian-Hyprland/assets/143619572/c1f96dfa-9787-460c-922c-b62abc004bba)
5.sudo apt install libdrm-dev python3-pip
6. Perform git clone of your directory
7. chmod +x install.sh
8. ./install.sh
9.  did not choose y for nvidia gpu question and selected y for remaining options

### Expected Behavior

Successful Hyprland installation 

### Actual Behavior

[What actually happened?]

### Screenshots
![image](https://github.com/JaKooLit/Debian-Hyprland/assets/143619572/c1b52a6d-1de3-499c-96fd-cf6d21179c56)
[hyprland_errors.txt](https://github.com/JaKooLit/Debian-Hyprland/files/15276418/hyprland_errors.txt)
[crashreport.txt](https://github.com/JaKooLit/Debian-Hyprland/files/15276419/crashreport.txt)

### Environment

- Linux Distro: Kali
- Linux Version : Kali 6.6.15-amd64
- Hyprland Version : 
![image](https://github.com/JaKooLit/Debian-Hyprland/assets/143619572/a8db8baf-cd85-41d9-96f9-6a6f33becb50)

- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]  : VM Oracle Vbox 7.0

**Comment by JaKooLit** [comment]
your nvidia is passthrough?

**Comment by Moorocks** [comment]
What do you mean passthrough? Did i get nvidia drivers i ran the command? -- No 
The command i ran did not return any nvidia drivers.
I ran this command : lspci | grep -i vga

**Comment by JaKooLit** [comment]
you just mentioned above 
"My nvidia drivers were not getting detected"

Plus the 

python3-pip https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/pywal.sh
libdrm-dev https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/00-dependencies.sh

was already part of the packages set to be installed

and also, VM on hyprland is a so so...

**Comment by JaKooLit** [comment]
> What do you mean passthrough? Did i get nvidia drivers i ran the command? -- No The command i ran did not return any nvidia drivers. I ran this command : lspci | grep -i vga
> 
> Now i ran into a different problem. I switched off the VM and opened it again, now it prompts me to enter password and when entered the screen just flashes and takes me back to login page :(
> 20240510-1530-54.6950178.mp4

did you enabled 3d acceleration?

**Comment by Moorocks** [comment]
Plus the

python3-pip https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/pywal.sh
libdrm-dev https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/00-dependencies.sh

was already part of the packages set to be installed

Oh I didn't know this, beacuse while i was watching a youtube video i observed that the user first checked nvidia thing and then installed those packages.

And when it comes to 3d acceleration, i just enabled it now and it seems to be working without any login issues. The mouse movement is kinda slow, might need to look at some quick tips and tricks.

Thanks for your help mate :)

**Comment by JaKooLit** [comment]
cant do anything with that slow mouse movement

you can search about it.. hyprland is meant to run on hardware

**Comment by Moorocks** [comment]
Thanks for your help mate, it there any way can i just install the hyprland terminal? it looks crazy though..
