### ISSUE TITLE
[Bug]: Red screen of death at lock and kitty opening black screen 

### ISSUE THREAD

**Issue by olterman** [JaKooLit/Debian-Hyprland#71]
### Description

Red screen of death at every lock (swaylock/hyperlock/wallok and kitty would open a black screen 

### Steps to Reproduce

1. install with your script 
2. lock screen or open kitty 

### Expected Behavior
screen to lock or kitty to open 

### Actual Behavior
Red screen of death on lock 

black screen for kitty 

### Environment

Debian 13 
Nvidia 

etc 

### Additional Information

I SOLVED IT!!!!
by 
# apt install libnvidia-egl-wayland1 

Maybe you should add this package in your script

**Comment by olterman** [comment]
on desktop, 

Machine 1 - GPU nvidia NVIDIA GeForce RTX 2070
Machine 2 - NVIDIA GeForce GTX 1060

same issue on both (red screen on any locking program and black (unresponsive kitty) 
The lock screen still doesnt have a large background (just black) but the thumbnail is there and all the time and weather, so functional! 

Also a note the SUPER - E, settings menu opens all settings in kitty even though the $terminal var is changed in UserKeybinds, maybe change so that  $terminal is used even for your menu's . it was a real hassle before I figured out the lib needed

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/a366acbfc58e8c8ebc6750995a859b471935dd66

regarding the universal terminal, well been trying to find a way to unify a variables..

But Im still struggling to find way..

for example, on waybar modules, opening tty based like nvtop or btop, I cant assign a unified tty for example..

In any case, I suggest you visit the wiki I have created

https://github.com/JaKooLit/Hyprland-Dots/wiki
