### ISSUE TITLE
rofi not showing any Flatpak apps 

### ISSUE THREAD

**Issue by olterman** [JaKooLit/Debian-Hyprland#72]
### Description

[Provide a clear and concise description of the bug.]
rofi -show drun  #not showing any Flatpak apps 

### Steps to Reproduce

1. SUPER - D 
2. No Flatpak apps shown 

### Expected Behavior

that the flatpak apps woould show in dmenu 

### Actual Behavior

can't see them, have to bind a whole lot of flatpak run kommands 

### Environment

- Linux Distro: Debian 13, SID
- Linux Version, 6.7

**Comment by JaKooLit** [comment]
log out and relogin or reboot

**Comment by olterman** [comment]
Oh I have many times ... they wont show up

**Comment by JaKooLit** [comment]
are you using rofi or rofi-wayland?

rofi from debian repo does not support wayland.. that could be the reason why

**Comment by olterman** [comment]
hmm, I installed from your script so was assuming, I was using the right
one.

Verum + Venia + Aequitas

http://www.olterman.se

**Comment by JaKooLit** [comment]
> hmm, I installed from your script so was assuming, I was using the right one. --- edit Checked now and no rofi debian package installed


Thanks just covering the bases....

I dont use flatpak but when I added discord - flatpak to my debian, it shows the discord ok

**Comment by olterman** [comment]
As I said on one of my two debian machines it works fine, trying to understand what the difference is .... So far no luck.

**Comment by JaKooLit** [comment]
did you install the zsh?

if can you try to install zplug? its plugin for zsh

**Comment by olterman** [comment]
Your script installed my zsh ... I have now installed zsh plugin ... dont know what to do with it or how to use it though

**Comment by JaKooLit** [comment]
So I want to give you update here

I have added this 

flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

instead of 
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo


Notice the --user

and then when I install something from flathub,

it will give me option wether to install on user or system ...

on my test if I choose user, it wont show on rofi... if I choose system, it will show on rofi...

**Comment by olterman** [comment]
All my flatpaks where installed as system .... 
I have now solved it by adding: 
env = XDG_DATA_DIRS,/usr/local/share/:/usr/share/:/var/lib/flatpak/exports/share
to ENVariables.conf
