### ISSUE TITLE
[Bug]: building failed during make command

### ISSUE THREAD

**Issue by opsboltz** [JaKooLit/Debian-Hyprland#78]
## Bug Report

While I was using the make command in the Hyprland Folder because i was hasving problems somewhere and i couldnt use the command so i went back and tried to find what it was so I found it. I know this is large but htis is what it gave me ive been trying to fix it for 2 days now and going through the bug reports on here and cant find anything, talking about this problem so i thought id bring it up.

"FAILED: CMakeFiles/Hyprland.dir/src/protocols/OutputManagement.cpp.o 
/usr/bin/c++ -DHAS_EXECINFO -DHyprland_EXPORTS -DLEGACY_RENDERER -DUSES_SYSTEMD -DWLR_USE_UNSTABLE -I/home/user/Debian-Hyprland/Hyprland/. -I/home/user/Debian-Hyprland/Hyprland/src -I/home/user/Debian-Hyprland/Hyprland/subprojects/wlroots-hyprland/include -I/home/user/Debian-Hyprland/Hyprland/subprojects/wlroots-hyprland/build/include -I/home/user/Debian-Hyprland/Hyprland/subprojects/udis86 -I/home/user/Debian-Hyprland/Hyprland/protocols -I/home/user/Debian-Hyprland/Hyprland/subprojects/udis86/libudis86 -isystem /usr/include/uuid -isystem /usr/include/cairo -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/pixman-1 -isystem /usr/include/pango-1.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/sysprof-6 -isystem /usr/include/harfbuzz -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/fribidi -isystem /usr/include/libdrm -O3 -DNDEBUG -std=gnu++23 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -pthread -Winvalid-pch -include /home/user/Debian-Hyprland/Hyprland/build/CMakeFiles/Hyprland.dir/cmake_pch.hxx -MD -MT CMakeFiles/Hyprland.dir/src/protocols/OutputManagement.cpp.o -MF CMakeFiles/Hyprland.dir/src/protocols/OutputManagement.cpp.o.d -o CMakeFiles/Hyprland.dir/src/protocols/OutputManagement.cpp.o -c /home/user/Debian-Hyprland/Hyprland/src/protocols/OutputManagement.cpp
/home/user/Debian-Hyprland/Hyprland/src/protocols/OutputManagement.cpp: In member function ‘void COutputHead::sendAllData()’:
/home/user/Debian-Hyprland/Hyprland/src/protocols/OutputManagement.cpp:169:64: error: cannot convert ‘wl_resource*’ to ‘CZwlrOutputModeV1*’
  169 |                 resource->sendCurrentMode(m->resource->resource());
      |                                           ~~~~~~~~~~~~~~~~~~~~~^~
      |                                                                |
      |                                                                wl_resource*
In file included from /home/user/Debian-Hyprland/Hyprland/src/protocols/OutputManagement.hpp:7,
                 from /home/user/Debian-Hyprland/Hyprland/src/protocols/OutputManagement.cpp:1:
/home/user/Debian-Hyprland/Hyprland/protocols/wlr-output-management-unstable-v1.hpp:216:26: note:   initializing argument 1 of ‘void CZwlrOutputHeadV1::sendCurrentMode(CZwlrOutputModeV1*)’
  216 |     void sendCurrentMode(CZwlrOutputModeV1*);
      |                          ^~~~~~~~~~~~~~~~~~
/home/user/Debian-Hyprland/Hyprland/src/protocols/OutputManagement.cpp: In member function ‘void COutputHead::updateMode()’:
/home/user/Debian-Hyprland/Hyprland/src/protocols/OutputManagement.cpp:200:64: error: cannot convert ‘wl_resource*’ to ‘CZwlrOutputModeV1*’
  200 |                 resource->sendCurrentMode(m->resource->resource());
      |                                        "

**Comment by opsboltz** [comment]
Sorry if this may not have been the best report I havent done to many reports

**Comment by JaKooLit** [comment]
> Sorry if this may not have been the best report I havent done to many reports

This hyprland folder is the downloaded by the script or you downloaded from hyprland github?

the script will download a specific branch from hyprland since that was the one I tested

the Debian-Hyprland folder will have Install-Logs folder

can you attach here the one with .....hyprland.log

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/6f63e32a928c32f55218138be2bff01b46891911

I just tried now and it does not build 

something must have changed... cause Ive tried it couple of days ago..

But weirdly enough, I can build the latest from master..

![Screenshot_15-May_11-18-58_29255](https://github.com/JaKooLit/Debian-Hyprland/assets/85185940/cc910dcc-5bad-4977-a3b6-6e37178f4ce9)


Anyway, to be on safe side, I just backed down to Hyprland v0.39.1 as having a Hyprland-git version for Debian is just inviting a disaster

**Comment by opsboltz** [comment]
Thanks!
