### ISSUE TITLE
Please help to uninstall the hyperland with the script

### ISSUE THREAD

**Issue by Parsa307** [JaKooLit/Debian-Hyprland#8]
Please i f*** my installation with your script

**Comment by Parsa307** [comment]
> if you want to remove hyprland, change to debian-hyprland folder first...
> 
> then CD Hyprland
> 
> and then sudo make uninstall
> 
> can you be more specific with the "fucked up" installation part?

Check the ksk royal commend i talked here it was Parsa kazemi

**Comment by skyisthela** [comment]
hey im not sure where to ask but how do i delete it? i can't cd to debain hyprland or hyprland

**Comment by Vdcds** [comment]
hey  I have a uninstall script on my side @JaKooLit where do I  contribute it

**Comment by JaKooLit** [comment]
you can submit a PR

**Comment by Vdcds** [comment]
okay dude cool.  happy to  help .. lemme fork and clone first

**Comment by Vdcds** [comment]
but hey @JaKooLit there's a short catch. I made it fedora specific (as i use fedora myself) only is that cool ?

**Comment by JaKooLit** [comment]
well lets see...

im interested on your approach

since when I tried few months ago, I didnt like end result so yeah.....

push to fedora-hyprland

**Comment by Vdcds** [comment]
okay.. no problem 
it worked fine for me, removed everything and reset it to the classic gnome fedora defaults 
lets see lemme push

**Comment by Vdcds** [comment]
hey @JaKooLit can you please check #105 at fedora-hyprland ... I have submitted PR there.  thanks !!

**Comment by JaKooLit** [comment]
you dont need to tag me and inform me since Im the owner, I received notifications


and be patient since I have also other things to do in my life

thank you

**Comment by Vdcds** [comment]
no worries. I was just trying to be helpful sorry if it irritated never meant to do that.
