### ISSUE TITLE
[Bug]: After installation and login with Hyprland, nothing changed still the same

### ISSUE THREAD

**Issue by SonwDev** [JaKooLit/Debian-Hyprland#90]
### Description
I alr done my installation and reboot then login with hyprland choice, after im in nothing changed still the same, just some terminal pokemons, that's all

- Linux Distro:  Ubuntu 24.04 LTS
- Linux Version, output of `uname -a`: Linux Trans 6.8.0-31-generic - Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
- Installation Environment: On The Main Hardware

**Comment by JaKooLit** [comment]
problem with Debian/Ubuntu is the pyprland plugin is a bit "picky" especially with ubuntu

you can just type exit in it... the tty is the drop down terminal for pyprland..

you can disable pyprland by editing 

~/.config/hypr/UserConfigs/Start_Apps.conf

look for the line pypr and comment it... delete or put # before it


and also, I need all the Install-Logs files which is inside Ubuntu-Hyprland directory

check all those and see for errors

**Comment by SonwDev** [comment]
> problem with Debian/Ubuntu is the pyprland plugin is a bit "picky" especially with ubuntu
> 
> you can just type exit in it... the tty is the drop down terminal for pyprland..
> 
> you can disable pyprland by editing
> 
> ~/.config/hypr/UserConfigs/Start_Apps.conf
> 
> look for the line pypr and comment it... delete or put # before it
> 
> and also, I need all the Install-Logs files which is inside Ubuntu-Hyprland directory
> 
> check all those and see for errors

oh i see that, package vulkan-validationlayers-dev and libgulkan failed to install, ill check it

**Comment by SonwDev** [comment]
> problem with Debian/Ubuntu is the pyprland plugin is a bit "picky" especially with ubuntu
> 
> you can just type exit in it... the tty is the drop down terminal for pyprland..
> 
> you can disable pyprland by editing
> 
> ~/.config/hypr/UserConfigs/Start_Apps.conf
> 
> look for the line pypr and comment it... delete or put # before it
> 
> and also, I need all the Install-Logs files which is inside Ubuntu-Hyprland directory
> 
> check all those and see for errors

here's all install logs today btw, ty
[install-25-04.zip](https://github.com/JaKooLit/Debian-Hyprland/files/15441708/install-25-04.zip)

**Comment by JaKooLit** [comment]
looks like you didnt choose to install dotfiles. I dont see in the log

**Comment by SonwDev** [comment]
> looks like you didnt choose to install dotfiles. I dont see in the log

i remember that i alr choose yes for dotfile, hm..., ill try install again.

**Comment by SonwDev** [comment]
> looks like you didnt choose to install dotfiles. I dont see in the log

[install-26-05.zip](https://github.com/JaKooLit/Debian-Hyprland/files/15445378/install-26-05.zip)
Hey!, here's all Install-Logs today
there's some packages that show errors i can't able to find somewhere to download them, i alr try to build Vulkan but still can't download somehow

**Comment by SonwDev** [comment]
oh and there's 3 ERRORS package that idk how to install manual, im tried and still don't how.

**Comment by JaKooLit** [comment]
nevermind about that... since most probably they are not present in ubuntu repo.. ive checked its not a very critical component as such

**Comment by JaKooLit** [comment]
so when you choose hyprland from log in manager, nothing happening? have you tried super w and choose a wallpaper?

**Comment by SonwDev** [comment]
> so when you choose hyprland from log in manager, nothing happening? have you tried super w and choose a wallpaper?

I tried, but all i got just blackscreen with normal cursor

**Comment by SonwDev** [comment]
> > so when you choose hyprland from log in manager, nothing happening? have you tried super w and choose a wallpaper?
> 
> I tried, but all i got just blackscreen with normal cursor, when i press super with some key the cursor still able to interact but nothing changed... still the same...

**Comment by JaKooLit** [comment]
do you have waybar? or its just blackscreen with cursor?

is there anything on the screen? can you move cursor?

**Comment by SonwDev** [comment]
> do you have waybar? or its just blackscreen with cursor?
> 
> is there anything on the screen? can you move cursor?

its just blackscreen, with the normsl cursor, i can move btw.

**Comment by JaKooLit** [comment]
nothing is happening by opening rofi super d
kitty super enter
super ctrl b

nothing?

can you show me picture?

can you join discord faster reply

**Comment by SonwDev** [comment]
> nothing is happening by opening rofi super d kitty super enter super ctrl b
> 
> nothing?
> 
> can you show me picture?
> 
> can you join discord faster reply

sure ill join the discord

**Comment by JaKooLit** [comment]
I cant find this post anymore on discord.. is this resolved?

**Comment by SonwDev** [comment]
> I cant find this post anymore on discord.. is this resolved?

no isn't, it just no one give solutions yet.

**Comment by JaKooLit** [comment]
is this a newly install ubuntu or upgrade to 24.04?

**Comment by SonwDev** [comment]
> is this a newly install ubuntu or upgrade to 24.04? 

is newly install ubuntu

**Comment by SonwDev** [comment]
> is this a newly install ubuntu or upgrade to 24.04? 

i think is missing some repository links

**Comment by SonwDev** [comment]
> > is this a newly install ubuntu or upgrade to 24.04? 
> 
> i think is missing some repository links, deb-src?

**Comment by JaKooLit** [comment]
Please try again... i have adjusted some things on the script

**Comment by SonwDev** [comment]
> Please try again... i have adjusted some things on the script
> 
> you need to download and a new Ubuntu-Hyprland install script. Please carry out as stated on readme. Dont install the one from Debian-Hyprland as showned by KSK... it is not compatible. Although I am amazed he succesfully installed using the Debian-Hyprland.
> 
> 

XD, surely

**Comment by SonwDev** [comment]
> Please try again... i have adjusted some things on the script
> 
> you need to download and a new Ubuntu-Hyprland install script. Please carry out as stated on readme. Dont install the one from Debian-Hyprland as showned by KSK... it is not compatible. Although I am amazed he succesfully installed using the Debian-Hyprland.
> 
> 

XD, surely

**Comment by SonwDev** [comment]
> Please try again... i have adjusted some things on the script
> 
> you need to download and a new Ubuntu-Hyprland install script. Please carry out as stated on readme. Dont install the one from Debian-Hyprland as showned by KSK... it is not compatible. Although I am amazed he succesfully installed using the Debian-Hyprland.

Hey! um, i just reinstall ur script
Goodnew is the installing progress works fine and all package are good!
Badnew is still the same problem rn.

**Comment by Nine-winged-Dragon** [comment]
安装完壁纸不显示出来黑屏，怎么回事儿，

**Comment by JaKooLit** [comment]
> 安装完壁纸不显示出来黑屏，怎么回事儿，

it is Debian / Ubuntu....

thats whats going on
