### ISSUE TITLE
[Bug]: 23.10.1 not working

### ISSUE THREAD

**Issue by nvmmonkey** [JaKooLit/Debian-Hyprland#91]
### Description

Ubuntu 23.10.1 from official .iso won't work, never try 23.10. ```git clone``` the correct branch.
But i managed to get it worked on 24.04 LTS. Shame that the docker desktop is not available on 24.04

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/tree/Ubuntu-24.04-LTS?tab=readme-ov-file#%EF%B8%8F-pre-requisites-and-very-important


as stated on readme, only designed for 24.04 LTS... older build wont work due to depencies
