### ISSUE TITLE
[Bug]: Dropdown terminal shortcut errors

### ISSUE THREAD

**Issue by 1blckhrt** [JaKooLit/Debian-Hyprland#92]
### Description

Unable to use dropdown terminal shortcut (Super + Shift + Enter) - met with 2 separate errors

### Steps to Reproduce

1. Install Ubuntu 24.04 in a dual boot setup
2. Run script to install as normal
3. Press keybind shortcut

### Expected Behavior

I expected the drop down terminal to appear

### Actual Behavior

In the top right, I get two different errors, they seem to alternate between each.

### Screenshots

![Screenshot_26-May_10-50-02_30964](https://github.com/JaKooLit/Debian-Hyprland/assets/143528734/1b6b9756-eceb-4b76-ae25-d86bcbfd4422)

First error: Pypr integrity check failed on scratchpads::run_toggle: No address!
Second error: Pypr error scratchpads::run_toggle: 'size'

### Environment

Linux Distro - Ubuntu 24.04
Linux Version - Linux 6.8.0-31-generic
Hyprland Version - v0.39.1
Installation Environment - Bare metal laptop, can provide specs upon request. Secure Boot off

### Extra

The only extra configuration I have done is uninstalled the "Oh my ZSH" config files and used powerlevel10k instead, as well as using pywal to make the terminal colors match the background.

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/blob/Ubuntu-24.04-LTS/README.md#-some-known-issues

" pyprland is a hit and miss. Drop down not working, zooming is hit and miss"

**Comment by 1blckhrt** [comment]
I completely missed that, apologies.
