### ISSUE TITLE
How to remove this 

### ISSUE THREAD

**Issue by amandeepsingh9999** [JaKooLit/Debian-Hyprland#95]
## Kindly help me with this
I am having some issue after installing it in my kali linux operation system can you guide so that i can remove it and install it again

**Comment by JaKooLit** [comment]
as stated on Readme, there is no uninstall script


you can simply re-run the script again if you want to reinstall

**Comment by amandeepsingh9999** [comment]
Brother can you help me with another issue i am having when i'm opening obs-studio in hyprland is does not show screen share option , while in normal ubuntu it show the screen share option

**Comment by JaKooLit** [comment]
> Brother can you help me with another issue i am having when i'm opening obs-studio in hyprland is does not show screen share option , while in normal ubuntu it show the screen share option

https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-screen-recording-like-obs

**Comment by amandeepsingh9999** [comment]
Hello brother sorry to bother you again but have you used any thing like kdeconnect or gsconnect it doesn't come to work for me

**Comment by JaKooLit** [comment]
I dont use any of those so no idea
